config/routes.rb
Caioduarte::Application.routes.draw do
  LOCALES = /en|pt\-BR/

  scope "(:locale)", :locale => LOCALES do
    resource :bio, :only => :show

    resource :jobs, :only => :show

    resource :contacts, :only => [:new, :create, :show], :path => 'contact'

    root :to => "home#index"

    namespace :admin do
      resources :jobs, :except => :show

      resources :users, :except => :show

      resource :bios, :only => [] do 
        collection do
          get 'edit_multiple'
          put 'update_multiple'
        end
      end

      resources :languages, :except => :show

      resource :user_sessions, :only => [:create, :new, :destroy], :path => 'login', :path_names => {:new => ''}

      root :to => "home#index"
    end
  end

  match '/:locale' => 'home#index', :locale => LOCALES
end

app/models/job.rb
class Job < ActiveRecord::Base
	has_many :job_descriptions, :dependent => :destroy, :autosave => :true
	has_many :thumbs, :dependent => :destroy, :autosave => :true

	default_scope order('created_at DESC')
	scope :to_display, where(:show => true)
	paginates_per 1

	after_create :verify_existence_of_thumbs

	accepts_nested_attributes_for :job_descriptions
	accepts_nested_attributes_for :thumbs

  attr_accessible :show, :job_descriptions_attributes, :thumbs_attributes

  protected

  def verify_existence_of_thumbs
  	if self.thumbs.count == 0
  		3.times do
	  		thumb = Thumb.new
	  		thumb.job= self
	  		thumb.save
  		end
  	end
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController
  before_filter :require_authentication, :only => [:create, :update, :destroy]
  
  def index
    @jobs = Kaminari.paginate_array(Job.all).page(params[:page]).per(3)
  end

  def new
    @job = Job.new
    3.times do 
      @job.thumbs.push Thumb.new
    end
    Language.all.each do |language|
      job_description = JobDescription.new
      job_description.language= language
      @job.job_descriptions.push job_description
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(params[:job])

    if @job.save
      redirect_to admin_jobs_path, :notice => t('flash.notice.job.created')
    else
      render action: "new"
    end
  end

  def update
    @job = Job.find(params[:id])

    if @job.update_attributes(params[:job])
      redirect_to admin_jobs_path, :notice => t('flash.notice.job.updated')
    else
      render action: "edit"
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    redirect_to admin_jobs_url
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_filter :set_page

	def show
		@jobs = Job.to_display.page(params[:page])
	end

	def set_page
		params[:page] = 1 unless params[:page]
	end
end

app/helpers/jobs_helper.rb
module JobsHelper
	def description_by_locale job
		JobDescription.by_locale(params[:locale]).where(:job_id => job).first
	end

	def jobs_count
		Job.to_display.count
	end

	def pagination_class index
		params[:page].to_i == (index+1) ? 'icon-circle' : 'icon-circle-blank'
	end
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <%= t 'general.form_error' %>
    </div>
  <% end %>

  <ul id="tabs">
    <% for job_description in @job.job_descriptions do %>
      <li>
        <a href="#" title="<%= job_description.language.locale %>">
          <%= image_tag job_description.language.flag, :height => '15' %>
          <span>
            <%= job_description.language.name %>
          </span>
        </a>
      </li>
    <% end %>
  </ul>

  <div id="tabs_contents">
    <%= f.fields_for :job_descriptions, @job.job_descriptions do |job_descriptions_fields| %>
      <%= job_descriptions_fields.hidden_field :language_id %>
      <div id="<%= job_descriptions_fields.object.language.locale %>">
        <p>
          <%= job_descriptions_fields.label :title %>
          <%= job_descriptions_fields.text_field :title %>
        </p>
        <p>
          <%= job_descriptions_fields.label :description %>
          <%= job_descriptions_fields.text_area :description %>
        </p>
      </div>
    <% end %>
  </div>

  <article id="article_pictures">
    <%= label_tag t('.thumbs') %>
    <span class="hint">
      <%= t('.thumbs_hint') %>
    </span>
    <p>
      <%= f.fields_for :thumbs, @job.thumbs[0] do |thumb_fields| %>
        <div id="thumb0" class="thumb">
          <% unless thumb_fields.object.picture.blank? %>
            <%= image_tag thumb_fields.object.picture.thumb %>
          <% else %>
            <div class="no_image"><span><%= t('.add_image') %></span></div>
          <% end %>
          <%= thumb_fields.file_field :picture %>
        </div>
      <% end %>
      <%= f.fields_for :thumbs, @job.thumbs[1] do |thumb_fields| %>
        <div id="thumb1" class="thumb">
          <% unless thumb_fields.object.picture.blank? %>
            <%= image_tag thumb_fields.object.picture.thumb %>
          <% else %>
            <div class="no_image"><span><%= t('.add_image') %></span></div>
          <% end %>
          <%= thumb_fields.file_field :picture %>
        </div>
      <% end %>
      <%= f.fields_for :thumbs, @job.thumbs[2] do |thumb_fields| %>
        <div id="thumb2" class="thumb">
          <% unless thumb_fields.object.picture.blank? %>
            <%= image_tag thumb_fields.object.picture.thumb %>
          <% else %>
            <div class="no_image"><span><%= t('.add_image') %></span></div>
          <% end %>
          <%= thumb_fields.file_field :picture %>
        </div>
      <% end %>
    </p>
    <p>
      <%= f.label :isShown %>
      <%= f.check_box :isShown %>
    </p>
  </article>

  <%= f.submit %>
  <span class='cancel_button'>
    <%= link_to t('links.cancel'), jobs_path %>
  </span>
<% end %>

app/views/jobs/_job.html.erb
<div id="job-description">
	<%= render 'job_description', :job_description => description_by_locale(job) %>
</div>
<div id="thumbs">
	<ul>
		<% job.thumbs.each_with_index do |thumb, index| %>
			<li>
				<div class="hexagon thumb<%= index %>">
					<div id="vlightbox1" class="hexagon-in">
						<%= link_to image_tag(thumb.picture.thumb), thumb.picture.to_s, :class => 'vlightbox1' %>
					</div>
				</div>
			</li>
		<% end %>
	</ul>
</div>

app/views/jobs/_job_description.html.erb
<h2><%= raw(job_description.title) %></h2>

<p>
	<%= raw(job_description.description) %>
</p>

app/views/jobs/_job_description_fields.html.erb
<fieldset>
  <legend>
    <%= image_tag :language %>
    <%= :language %>
  </legend>
  <ul>
    <li>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </li>
    <li>
      <%= f.label :description %><br />
      <%= f.text_area :description %>
    </li>
  </ul>
</fieldset>

app/views/jobs/_pagination.html.erb
<div id="pagination">
	<nav>
		<ul>
			<% jobs_count.times do |index| %>
				<li>
					<%= link_to raw("<i class=\"#{pagination_class index}\"></i>"), :page => (index+1) %>
				</li>
			<% end %>
		</ul>
	</nav>
</div>

app/views/jobs/index.html.erb
<h2><%= t '.title' %></h2>

<br />

<span class="add_button">
  <%= link_to t('links.add'), new_job_path %>
</span>

<br />
<br />

<% @jobs.each do |job| %>
  <article class="item">
    <div>
      <%= label_tag job.job_descriptions[0], t('activerecord.attributes.job_description.title') %>
      <%= job.job_descriptions[0].title %>
    </div>
    <div>
      <%= label_tag t('activerecord.attributes.job.isShown') %>
      <%= job.isShown ? raw('<i class="icon-ok green"></i>') : raw('<i class="icon-remove red"></i>') %>
    </div>
    <br/>
    <br/>
    <div>
      <% unless job.thumbs[0].picture.blank? %>
        <%= image_tag job.thumbs[0].picture.thumb %>
      <% else %>
        <div class="no_image"><span><%= t('.no_image') %></span></div>
      <% end %>
    </div>
    <div>
      <% unless job.thumbs[1].picture.blank? %>
        <%= image_tag job.thumbs[1].picture.thumb %>
      <% else %>
        <div class="no_image"><span><%= t('.no_image') %></span></div>
      <% end %>
    </div>
    <div>
      <% unless job.thumbs[2].picture.blank? %>
        <%= image_tag job.thumbs[2].picture.thumb %>
      <% else %>
        <div class="no_image"><span><%= t('.no_image') %></span></div>
      <% end %>
    </div>

    <div class="icons">
      <%= link_to raw('<i class="icon-edit icon-large"></i>'), edit_job_path(job) %>
      <%= link_to raw('<i class="icon-remove icon-large"></i>'), job, method: :delete, data: { :confirm => t('dialogs.confirm') } %>
    </div>
  </article>
<% end %>

app/views/jobs/show.html.erb
<%= render @jobs %>

<%= render 'pagination' %>