config/routes.rb
Caioduarte::Application.routes.draw do
  LOCALES = /en|pt\-BR/

  scope "(:locale)", :locale => LOCALES do
    resource :bio, :only => :show

    resource :jobs, :only => :show

    resource :contacts, :only => [:new, :create, :show], :path => 'contact'

    root :to => "home#index"

    namespace :admin do
      resources :jobs, :except => :show

      resources :users, :except => :show

      resource :bios, :only => [] do 
        collection do
          get 'edit_multiple'
          put 'update_multiple'
        end
      end

      resources :languages, :except => :show

      resource :user_sessions, :only => [:create, :new, :destroy], :path => 'login', :path_names => {:new => ''}

      root :to => "home#index"
    end
  end

  match '/:locale' => 'home#index', :locale => LOCALES
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation

  validates_presence_of :name, :email
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates_uniqueness_of :email

  has_secure_password

  def self.authenticate email, password
  	find_by_email(email).try(:authenticate, password)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :require_authentication, :only => [:create, :update, :destroy]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to admin_users_path, :notice => t('flash.notice.user.created')
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to admin_users_path, :notice => t('flash.notice.user.updated')
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to admin_users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_authentication, :only => [:create, :update, :destroy]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to users_path, :notice => t('flash.notice.user.created')
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to users_path, :notice => t('flash.notice.user.updated')
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <%= t 'general.form_error' %>
    </div>
  <% end %>

  <article>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= error_tag @user, :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= error_tag @user, :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      <%= error_tag @user, :password_confirmation %>
    </p>
    <p>
      <%= f.label :isAdmin %>
      <%= f.check_box :isAdmin %>
    </p>
  </article>
    
  <%= f.submit %>
  <span class='cancel_button'>
    <%= link_to t('links.cancel'), users_path %>
  </span>
<% end %>

app/views/users/index.html.erb
<h2><%= t '.title' %></h2>

<br />

<span class="add_button">
  <%= link_to t('links.add'), new_user_path %>
</span>

<br />
<br />

<% @users.each do |user| %>
	<article class="item">
		<div>
	  	<%= label_tag t('activerecord.attributes.user.email') %>
	    <%= user.email %>
    </div>
    <div>
	  	<%= label_tag t('activerecord.attributes.user.isAdmin') %>
	  	<span>
	    	<%= user.isAdmin ? raw('<i class="icon-ok green"></i>') : raw('<i class="icon-remove red"></i>') %>
	  	</span>
	  </div>		

	  <div class="icons">
    	<%= link_to raw('<i class="icon-edit icon-large"></i>'), edit_user_path(user) %>
  	  <%= link_to raw('<i class="icon-remove icon-large"></i>'), user, method: :delete, data: { :confirm => t('dialogs.confirm') } %>
		</div>
	</article>
<% end %>